service: coders-cantabria
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  alexa:
    handler: src/index.handler
    events:
      - alexaSkill: ${env:SKILL_ID} # Loaded from .env file